// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package g5.ambience;

import g5.ambience.BundleEntityPK;
import java.io.Serializable;

privileged aspect BundleEntityPK_Roo_Serializable {
    
    declare parents: BundleEntityPK implements Serializable;
    
    private static final long BundleEntityPK.serialVersionUID = 1L;
    
}
