// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package g5.ambience;

import g5.ambience.BundleEntityPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BundleEntityPK_Roo_Configurable {
    
    declare @type: BundleEntityPK: @Configurable;
    
}
