// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package g5.ambience;

import g5.ambience.ItemEntity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ItemEntity_Roo_Configurable {
    
    declare @type: ItemEntity: @Configurable;
    
}
