// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package g5.ambience;

import g5.ambience.UserEntity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserEntity_Roo_Configurable {
    
    declare @type: UserEntity: @Configurable;
    
}
