// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package g5.ambience.domain;

import g5.ambience.domain.BundleEntity;
import g5.ambience.domain.BundleEntityDataOnDemand;
import g5.ambience.domain.BundleEntityIntegrationTest;
import g5.ambience.domain.BundleEntityPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BundleEntityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BundleEntityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BundleEntityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BundleEntityIntegrationTest: @Transactional;
    
    @Autowired
    private BundleEntityDataOnDemand BundleEntityIntegrationTest.dod;
    
    @Test
    public void BundleEntityIntegrationTest.testCountBundleEntitys() {
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to initialize correctly", dod.getRandomBundleEntity());
        long count = BundleEntity.countBundleEntitys();
        Assert.assertTrue("Counter for 'BundleEntity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BundleEntityIntegrationTest.testFindBundleEntity() {
        BundleEntity obj = dod.getRandomBundleEntity();
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to initialize correctly", obj);
        BundleEntityPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to provide an identifier", id);
        obj = BundleEntity.findBundleEntity(id);
        Assert.assertNotNull("Find method for 'BundleEntity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BundleEntity' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BundleEntityIntegrationTest.testFindAllBundleEntitys() {
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to initialize correctly", dod.getRandomBundleEntity());
        long count = BundleEntity.countBundleEntitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'BundleEntity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BundleEntity> result = BundleEntity.findAllBundleEntitys();
        Assert.assertNotNull("Find all method for 'BundleEntity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BundleEntity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BundleEntityIntegrationTest.testFindBundleEntityEntries() {
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to initialize correctly", dod.getRandomBundleEntity());
        long count = BundleEntity.countBundleEntitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BundleEntity> result = BundleEntity.findBundleEntityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BundleEntity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BundleEntity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BundleEntityIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to initialize correctly", dod.getRandomBundleEntity());
        BundleEntity obj = dod.getNewTransientBundleEntity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BundleEntity' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BundleEntityIntegrationTest.testRemove() {
        BundleEntity obj = dod.getRandomBundleEntity();
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to initialize correctly", obj);
        BundleEntityPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BundleEntity' failed to provide an identifier", id);
        obj = BundleEntity.findBundleEntity(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BundleEntity' with identifier '" + id + "'", BundleEntity.findBundleEntity(id));
    }
    
}
