// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package g5.ambience.domain;

import g5.ambience.domain.BundleEntityDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BundleEntityDataOnDemand_Roo_Configurable {
    
    declare @type: BundleEntityDataOnDemand: @Configurable;
    
}
