// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package g5.ambience.domain;

import g5.ambience.domain.ItemEntity;
import g5.ambience.domain.ItemEntityDataOnDemand;
import g5.ambience.domain.ItemEntityIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ItemEntityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ItemEntityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ItemEntityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ItemEntityIntegrationTest: @Transactional;
    
    @Autowired
    private ItemEntityDataOnDemand ItemEntityIntegrationTest.dod;
    
    @Test
    public void ItemEntityIntegrationTest.testCountItemEntitys() {
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to initialize correctly", dod.getRandomItemEntity());
        long count = ItemEntity.countItemEntitys();
        Assert.assertTrue("Counter for 'ItemEntity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ItemEntityIntegrationTest.testFindItemEntity() {
        ItemEntity obj = dod.getRandomItemEntity();
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to initialize correctly", obj);
        Integer id = obj.getItemId();
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to provide an identifier", id);
        obj = ItemEntity.findItemEntity(id);
        Assert.assertNotNull("Find method for 'ItemEntity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ItemEntity' returned the incorrect identifier", id, obj.getItemId());
    }
    
    @Test
    public void ItemEntityIntegrationTest.testFindAllItemEntitys() {
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to initialize correctly", dod.getRandomItemEntity());
        long count = ItemEntity.countItemEntitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'ItemEntity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ItemEntity> result = ItemEntity.findAllItemEntitys();
        Assert.assertNotNull("Find all method for 'ItemEntity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ItemEntity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ItemEntityIntegrationTest.testFindItemEntityEntries() {
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to initialize correctly", dod.getRandomItemEntity());
        long count = ItemEntity.countItemEntitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ItemEntity> result = ItemEntity.findItemEntityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ItemEntity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ItemEntity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ItemEntityIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to initialize correctly", dod.getRandomItemEntity());
        ItemEntity obj = dod.getNewTransientItemEntity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ItemEntity' identifier to be null", obj.getItemId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ItemEntity' identifier to no longer be null", obj.getItemId());
    }
    
    @Test
    public void ItemEntityIntegrationTest.testRemove() {
        ItemEntity obj = dod.getRandomItemEntity();
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to initialize correctly", obj);
        Integer id = obj.getItemId();
        Assert.assertNotNull("Data on demand for 'ItemEntity' failed to provide an identifier", id);
        obj = ItemEntity.findItemEntity(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ItemEntity' with identifier '" + id + "'", ItemEntity.findItemEntity(id));
    }
    
}
